# fly.toml app configuration file generated for site-done-now on 2024-03-22T14:53:00-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'site-done-now'
primary_region = 'ord'

[build]

[http_service]
  internal_port = 4500
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
